languaje: node_js
node_js:
  - 15.7.0
script:
  - node index.js

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: .
  skip_cleanup: true
  on:
    tags: false
    branches:
      only:
        - main